### ISSUE TITLE
Bug on last four problems

### ISSUE THREAD

**Issue by hacking** [tmilev/calculator#2]
I'm not able to submit the answer for the last four problems, the answers are left blank.... I think that's a bug.

This is for Calculus 1.

Screenshot:
![ss 2017-05-21 at 02 33 12](https://cloud.githubusercontent.com/assets/24629980/26286390/8a37588c-3e32-11e7-8f4d-0d39baa23b54.png)

**Comment by tmilev** [comment]
Indeed, a bug, I've just fixed it (it was a <canvas tag that was not balanced properly with >. 
Apologies for the issue.
