### ISSUE TITLE
repeated parsing issue on 5.3.1.1

### ISSUE THREAD

**Issue by mariama741** [tmilev/calculator#3]
![screenshot 2017-08-09 22 45 53](https://user-images.githubusercontent.com/30885523/29152348-02dbe602-7d55-11e7-86ea-7896e9515f1b.png)

answers are unable to be submitted. because of parsing problem. even on practice problems, correct answers do not get marked correct.
link: https://calculator-algebra.org/cgi-bin/calculator?request=exercise&request=exercise&G_ENABLED_IDPS=google&activationToken=&debugFlag=&chapter=&courseHome=pagetemplates/UMB-Math130-2017-Summer.html&fileName=DefaultProblemLocation%2fLogarithm-of-quadratic-equation-1.html&topicList=topiclists/UMB-Math130.txt&studentView=false&

**Comment by tmilev** [comment]
I can't seem to reproduce the issue. Can you show me your actual quiz problem with a submission that is marked as wrong?

**Comment by mariama741** [comment]
![screenshot 2017-08-10 05 07 26](https://user-images.githubusercontent.com/30885523/29163390-560f690e-7d8a-11e7-961a-9c57d04da96f.png)

the submission is never marked, as there seems to be errors when I submit the answer.

![screenshot 2017-08-10 05 09 36](https://user-images.githubusercontent.com/30885523/29163434-7837dd0e-7d8a-11e7-83a6-28ad3a253b54.png)

on this one, I entered the correct answer on the practice problem, but it still failed to parse the answer.

**Comment by tmilev** [comment]
Your syntax appears to be wrong in both submissions: in both submissions, the comma is inside the radical, which is not allowed, and in one of the submissions you wrote 
+5
You should write 
5 
instead (omit the + in the front). 

For your quiz problem, here's how you should format it:

\left(\sqrt{\frac{1}{8} \left(5^{28}-7\right)}, - \sqrt{\frac{1}{8} \left(5^{28}-7\right)}\right)


You can just take the characters above, copy and paste them in the system and it should be understood.

**Comment by mariama741** [comment]
thank you! sorry to bother again, but on this problem, there doesn't appear to be a second side on the triangle
![screenshot 2017-08-10 18 29 41](https://user-images.githubusercontent.com/30885523/29194949-00a4e712-7dfa-11e7-9a8e-d78ee0c6828d.png)
?

**Comment by tmilev** [comment]
Thanks for the report. This is indeed a visual bug: if you zoom in with the mouse wheel you will find that two numbers are overlaid on top of one another. I will add an extra point to your grade for this problem.
