### ISSUE TITLE
polynomial division question

### ISSUE THREAD

**Issue by mariama741** [tmilev/calculator#4]
The answer on this question is marked incorrect, but the same answer later in the problem is marked correct. 
![screenshot 2017-08-10 21 53 06](https://user-images.githubusercontent.com/30885523/29198935-535b48ea-7e16-11e7-91d3-3b65e766e2bd.png)

![screenshot 2017-08-10 21 53 11](https://user-images.githubusercontent.com/30885523/29198940-58314d38-7e16-11e7-8714-0807135c2ae6.png)

**Comment by tmilev** [comment]
Thanks for the report, this is a genuine bug. It is now fixed. I manually add the missing points to your score. The bug fix has not been deployed yet, will come with next update.
